### ISSUE TITLE
Play-Leetcode/0021-Merge-Two-Sorted-Lists/cpp-0021/main.cpp

### ISSUE THREAD

**Issue by youfanFu1992** [liuyubobobo/Play-Leetcode#18]
波波老师您好，请问Play-Leetcode/0021-Merge-Two-Sorted-Lists/cpp-0021/main.cpp里面为什么要写第46行呢？
`dummyHead->next = NULL;`
谢谢！

**Comment by liuyubobobo** [comment]
性惯性地手动断开 dummyHead 和后面链表的内容，但不写完全没问题，其实是多余的：）
