### ISSUE TITLE
LeetCode 111. Minimum Depth of Binary Tree 测试用例有疑问

### ISSUE THREAD

**Issue by Aierhaimian** [liuyubobobo/Play-Leetcode#2]
老师您好，
当我对
[]
[null]
这两个测试用例进行测试时，我的代码输出
0
0
但是Expected
0
1
好诡异，不过我的代码提交是可以AC的，哈哈哈。

**Comment by liuyubobobo** [comment]
你的代码的输出结果是正确的：）
