### ISSUE TITLE
0001-Two-Sum第一种解决方案的边界处理存在Bug

### ISSUE THREAD

**Issue by franklee0902** [liuyubobobo/Play-Leetcode#20]
比如测试改成：[0, 4, 3, 5]，此时target=10，返回的结果是[3,3]。题目中要求是：不能重复利用这个数组中同样的元素，所以需要把外层循环的判断调整为：nums.length-1。

当然，根据题目中给出的假设：假设每种输入只会对应一个答案，所以不会有我们这样的case，所以处不处理都可以通过测试。

**Comment by liuyubobobo** [comment]
这个测试用例无解。对于我的代码，无论是 C++ 还是 Java 都会直接抛异常。因为题目输入保证了有解。

和外层循环没有关系。因为在 i = nums.size() - 1 的时候，j 从 i + 1，即 nums.size()开始，直接不满足循环条件，直接跳出了。这个代码是正确的，没有边界问题。

**Comment by franklee0902** [comment]
波波老师，是Java版本的Solution1中的代码，j每次都是从0开始的，所以会有这个问题。

```
for(int i = 0 ; i < nums.length; i ++)
            for(int j = 0 ; j < nums.length ; j ++)
                if(nums[i] + nums[j] == target){
                    int[] res = {i, j};
                    return res;
                }

throw new IllegalStateException("the input has no solution");
```
