### ISSUE TITLE
波波老师你好，1171题代码有点问题

### ISSUE THREAD

**Issue by skierlin** [liuyubobobo/Play-Leetcode#27]
老师你这道题思路很好，但是对于[1,3,2,-3,-2,5,5,-5,1]这个测试用例，算前缀和，算到2的时候，出现了一次6，然后到5的时候又出现了一次6，但是实际上我们已经把从3- -2这部分删除掉了，所以每次删除中间部分元素的时候，也需要把计算中间部分的map中保存的对应内容也给删掉才可以~

**Comment by liuyubobobo** [comment]
感谢提醒，你是对的，代码已经修正。

另外，发现这个问题最多只有 1000 个节点，所以暴力枚举就 ok，然后添加了一个 O(n^2) 的算法：）
