### ISSUE TITLE
64号题，cpp, main2的解法

### ISSUE THREAD

**Issue by maoliming** [liuyubobobo/Play-Leetcode#6]
res[1][0] = grid[0][0] + res[0][0];    
这条代码是不是有问题呀？应该是res[1][0] = grid[1][0] + res[0][0]
当然直接改的话会出错，因为grid[1][0]可能会发生越界
在下面的for循环中，res[i%2][0] = grid[i][0] + res[(i-1)%2][0];这条代码已经计算了res[1][0]
综上所述， res[1][0] = grid[0][0] + res[0][0];  这条代码时错误而且多余的

**Comment by liuyubobobo** [comment]
你是对的。谢谢你。已修改：）
