### ISSUE TITLE
377题，main2.cpp出现signed integer overflow

### ISSUE THREAD

**Issue by maoliming** [liuyubobobo/Play-Leetcode#7]
波波老师，第377题，当测试用例是[3,33,333] 10000时，用递归的方法可以通过，但是当用动态规划的方法main2.cpp时，会出现signed integer overflow的错误，将vector<int> memo改成vector<long long> memo也仍然会出现这个错误

**Comment by maoliming** [comment]
本地测试可以通过，leetcode上不能通过，不知道啥原因

**Comment by liuyubobobo** [comment]
wow! cool! 感谢提醒！看来Leetcode加了数据，存在某些中间解超级大，会溢出的情况。我试了一下，甚至long long都不够！

但是由于题目保证了最终的解是在int范围里，所以，这些超级大的中间解，是可以扔掉的。这也是记忆化搜索没有问题的原因。因为记忆化搜索是从target倒退，达到的中间状态，一定是可以得到最终解的中间步骤，所以，根据题目定义，一定在int范围里。

我已经对程序进行了修改。在dp过程中，对于memo[i]的更新，我会转成long long判断一下有没有超过int的最大值，如果超过了，就记为-1。根据题意，这些中间值，肯定不会最后用于构成target的。

在最后，我也添加了一个assert，来验证这一点：）

可以参考：[https://github.com/liuyubobobo/Play-Leetcode/blob/master/0377-Combination-Sum-IV/cpp-0377/main2.cpp](https://github.com/liuyubobobo/Play-Leetcode/blob/master/0377-Combination-Sum-IV/cpp-0377/main2.cpp)

谢谢：）
