### ISSUE TITLE
使用long long num = abs(x) 不能解决溢出问题

### ISSUE THREAD

**Issue by maoliming** [liuyubobobo/Play-Leetcode#8]
对于main.cpp中的代码，当测试用例是-2147483648仍然会报溢出错误。
Line 8: Char 28: runtime error: negation of -2147483648 cannot be represented in type 'int'; cast to an unsigned type to negate this value to itself (solution.cpp)
改成下面的代码就OK了
long long num = abs((long long)x);

**Comment by liuyubobobo** [comment]
抱歉，你说的是几号问题？

**Comment by maoliming** [comment]
0007-Reverse-Integer/cpp-0007/main.cpp

**Comment by liuyubobobo** [comment]
你是正确的，已修正，感谢提醒：）
